// Canonical server item manifest.
//
// Seeded generation imports this data so loot preview, sim runtime, and
// validation all read the same artifact and consumable catalog.

const ARTIFACT_SPECIAL_IDS = [
  'autoDecoys',
  'burnFuel',
  'burnRecharge',
  'burnReverseWells',
  'deathTeleport',
  'eddyDuration',
  'emergencyMassLock',
  'ghostTrailBeacon',
  'ghostWreckLoot',
  'inhibitorBlindPing',
  'instantFlowLock',
  'maxEddies',
  'overloadBleed',
  'pulseInvert',
  'pulseStandingWave',
  'recallBeacon',
  'signalAfterimage',
  'swarmDrainImmunity',
  'thrustSignalZero',
  'universalDampening',
  'wakeCloakCooldown',
];

const CONSUMABLE_EFFECT_IDS = [
  'breachFlare',
  'cargoJettison',
  'emergencyThrust',
  'shieldBurst',
  'signalFlare',
  'signalPurge',
  'timeSlowLocal',
  'wellRepulsor',
];

const ITEM_CATALOG = {
  1: [
    { id: 'patched-thruster', name: 'Patched Thruster', tier: 1, affinity: null, coefficients: { thrustScale: 1.08 }, value: [15, 25] },
    { id: 'scrap-plating', name: 'Scrap Plating', tier: 1, affinity: null, coefficients: { wellResistScale: 1.06 }, value: [15, 20] },
    { id: 'signal-baffle', name: 'Signal Baffle', tier: 1, affinity: null, coefficients: { signalGenMult: 0.93 }, value: [18, 28] },
    { id: 'worn-coupling', name: 'Worn Coupling', tier: 1, affinity: null, coefficients: { currentCoupling: 1.06 }, value: [15, 22] },
    { id: 'drag-foil', name: 'Drag Foil', tier: 1, affinity: null, coefficients: { dragScale: 0.94 }, value: [15, 20] },
    { id: 'cargo-netting', name: 'Cargo Netting', tier: 1, affinity: null, coefficients: { cargoSlots: 1 }, value: [20, 30] },
    { id: 'pulse-lens', name: 'Pulse Lens', tier: 1, affinity: null, coefficients: { pulseRadiusScale: 1.10 }, value: [18, 25] },
    { id: 'sensor-dish', name: 'Sensor Dish', tier: 1, affinity: null, coefficients: { sensorRange: 1.10 }, value: [15, 22] },
    { id: 'flow-vane', name: 'Flow Vane', tier: 1, affinity: 'drifter', coefficients: { currentCoupling: 1.08 }, value: [18, 25] },
    { id: 'burn-canister', name: 'Burn Canister', tier: 1, affinity: 'breacher', coefficients: {}, value: [18, 25], special: 'burnFuel+3' },
    { id: 'quiet-suture', name: 'Quiet Suture', tier: 1, affinity: 'shroud', coefficients: { signalGenMult: 0.96, controlDebuffResist: 1.04 }, value: [20, 30] },
    { id: 'freight-hook', name: 'Freight Hook', tier: 1, affinity: 'hauler', coefficients: { pickupRadius: 1.08 }, value: [18, 28] },
  ],
  2: [
    { id: 'tuned-thruster', name: 'Tuned Thruster', tier: 2, affinity: null, coefficients: { thrustScale: 1.15 }, value: [50, 80] },
    { id: 'gravity-sheath', name: 'Gravity Sheath', tier: 2, affinity: null, coefficients: { wellResistScale: 1.15 }, value: [55, 85] },
    { id: 'signal-dampener', name: 'Signal Dampener', tier: 2, affinity: null, coefficients: { signalGenMult: 0.85 }, value: [60, 90] },
    { id: 'decay-accelerator', name: 'Decay Accelerator', tier: 2, affinity: null, coefficients: { signalDecayMult: 1.20 }, value: [55, 85] },
    { id: 'current-amplifier', name: 'Current Amplifier', tier: 2, affinity: 'drifter', coefficients: { currentCoupling: 1.18 }, value: [60, 90] },
    { id: 'afterburner-injector', name: 'Afterburner Injector', tier: 2, affinity: 'breacher', coefficients: { thrustScale: 1.12, signalGenMult: 1.10 }, value: [55, 80] },
    { id: 'resonance-coil', name: 'Resonance Coil', tier: 2, affinity: 'resonant', coefficients: { pulseRadiusScale: 1.20, pulseCooldownScale: 0.90 }, value: [65, 95] },
    { id: 'ghost-weave', name: 'Ghost Weave', tier: 2, affinity: 'shroud', coefficients: { signalGenMult: 0.82, sensorRange: 1.12 }, value: [70, 100] },
    { id: 'cargo-brace', name: 'Cargo Brace', tier: 2, affinity: 'hauler', coefficients: { cargoSlots: 1, pickupRadius: 1.10 }, value: [60, 90] },
    { id: 'pulse-sharpener', name: 'Pulse Sharpener', tier: 2, affinity: null, coefficients: { pulseSignalScale: 0.80, pulseRadiusScale: 0.90 }, value: [50, 75] },
    { id: 'debuff-purge', name: 'Debuff Purge', tier: 2, affinity: null, coefficients: { controlDebuffResist: 1.30 }, value: [50, 75] },
    { id: 'hull-reinforcement', name: 'Hull Reinforcement', tier: 2, affinity: null, coefficients: { wellResistScale: 1.10, controlDebuffResist: 1.15 }, value: [55, 85] },
    { id: 'drag-coefficient', name: 'Drag Coefficient', tier: 2, affinity: null, coefficients: { dragScale: 0.88 }, value: [55, 80] },
    { id: 'pickup-magnet', name: 'Pickup Magnet', tier: 2, affinity: null, coefficients: { pickupRadius: 1.25 }, value: [50, 75] },
    { id: 'mass-stitcher', name: 'Mass Stitcher', tier: 2, affinity: 'hauler', coefficients: { cargoSlots: 1, wellResistScale: 1.08 }, value: [65, 95] },
    { id: 'echo-sink', name: 'Echo Sink', tier: 2, affinity: 'shroud', coefficients: { signalDecayMult: 1.18, sensorRange: 0.92 }, value: [60, 90] },
    { id: 'wake-needle', name: 'Wake Needle', tier: 2, affinity: 'resonant', coefficients: { pulseCooldownScale: 0.88, pulseSignalScale: 1.10 }, value: [65, 95] },
  ],
  3: [
    { id: 'dead-mans-thruster', name: "Dead Man's Thruster", tier: 3, affinity: 'drifter', coefficients: { signalGenMult: 0.0, dragScale: 1.30 }, value: [200, 320], special: 'thrustSignalZero' },
    { id: 'overcharged-core', name: 'Overcharged Core', tier: 3, affinity: 'breacher', coefficients: { thrustScale: 1.30, signalGenMult: 1.50, signalDecayMult: 0.70 }, value: [220, 350] },
    { id: 'harmonic-anchor', name: 'Harmonic Anchor', tier: 3, affinity: 'resonant', coefficients: {}, value: [250, 380], special: 'eddyDuration+4,maxEddies+2' },
    { id: 'phase-veil', name: 'Phase Veil', tier: 3, affinity: 'shroud', coefficients: {}, value: [240, 360], special: 'ghostTrailBeacon,wakeCloakCooldown-15' },
    { id: 'cargo-brace-mk2', name: 'Cargo Brace Mk II', tier: 3, affinity: 'hauler', coefficients: {}, value: [230, 340], special: 'swarmDrainImmunity3' },
    { id: 'tidal-resonator', name: 'Tidal Resonator', tier: 3, affinity: null, coefficients: {}, value: [200, 300], special: 'pulseStandingWave' },
    { id: 'well-skimmer', name: 'Well Skimmer', tier: 3, affinity: null, coefficients: { wellResistScale: 1.35, thrustScale: 0.90 }, value: [210, 320] },
    { id: 'signal-siphon', name: 'Signal Siphon', tier: 3, affinity: null, coefficients: { signalDecayMult: 1.50, signalGenMult: 1.15 }, value: [200, 310] },
    { id: 'precision-pulse', name: 'Precision Pulse', tier: 3, affinity: null, coefficients: { pulseRadiusScale: 0.60, pulseSignalScale: 0.40, pulseCooldownScale: 0.50 }, value: [220, 340] },
    { id: 'drift-engine', name: 'Drift Engine', tier: 3, affinity: 'drifter', coefficients: { currentCoupling: 1.40, thrustScale: 0.75 }, value: [230, 350] },
    { id: 'burn-extender', name: 'Burn Extender', tier: 3, affinity: 'breacher', coefficients: {}, value: [250, 370], special: 'burnFuel+15,burnRecharge×2' },
    { id: 'sensor-array', name: 'Sensor Array', tier: 3, affinity: null, coefficients: { sensorRange: 1.50, signalGenMult: 1.08 }, value: [200, 300] },
    { id: 'event-horizon-keel', name: 'Event Horizon Keel', tier: 3, affinity: 'breacher', coefficients: { thrustScale: 1.18, wellResistScale: 1.20, dragScale: 1.12 }, value: [240, 360], special: 'emergencyMassLock' },
    { id: 'negative-space-spool', name: 'Negative Space Spool', tier: 3, affinity: 'shroud', coefficients: { signalGenMult: 0.76, pickupRadius: 0.85 }, value: [240, 360], special: 'signalAfterimage' },
    { id: 'braided-eddy-core', name: 'Braided Eddy Core', tier: 3, affinity: 'resonant', coefficients: { currentCoupling: 1.18, pulseRadiusScale: 1.12 }, value: [240, 360], special: 'eddyDuration+2,maxEddies+1' },
  ],
  4: [
    { id: 'gravity-lens', name: 'Gravity Lens', tier: 4, affinity: 'resonant', coefficients: {}, value: [800, 1200], special: 'pulseInvert' },
    { id: 'echo-chamber', name: 'Echo Chamber', tier: 4, affinity: 'shroud', coefficients: {}, value: [900, 1300], special: 'autoDecoys' },
    { id: 'void-anchor', name: 'Void Anchor', tier: 4, affinity: null, coefficients: {}, value: [800, 1100], special: 'recallBeacon' },
    { id: 'singularity-drive', name: 'Singularity Drive', tier: 4, affinity: 'breacher', coefficients: {}, value: [1000, 1500], special: 'burnReverseWells' },
    { id: 'laminar-flow-core', name: 'Laminar Flow Core', tier: 4, affinity: 'drifter', coefficients: {}, value: [900, 1300], special: 'instantFlowLock' },
    { id: 'salvage-titan', name: 'Salvage Titan', tier: 4, affinity: 'hauler', coefficients: { cargoSlots: 3 }, value: [800, 1200], special: 'ghostWreckLoot' },
    { id: 'inhibitor-resonance', name: 'Inhibitor Resonance', tier: 4, affinity: null, coefficients: {}, value: [850, 1200], special: 'universalDampening' },
    { id: 'temporal-displacement', name: 'Temporal Displacement', tier: 4, affinity: null, coefficients: {}, value: [900, 1300], special: 'deathTeleport' },
    { id: 'cinder-geometry', name: 'Cinder Geometry', tier: 4, affinity: 'breacher', coefficients: { thrustScale: 1.25, signalGenMult: 1.25 }, value: [850, 1250], special: 'overloadBleed' },
    { id: 'last-wake-codex', name: 'Last Wake Codex', tier: 4, affinity: null, coefficients: { sensorRange: 1.35, signalDecayMult: 1.20 }, value: [900, 1300], special: 'inhibitorBlindPing' },
  ],
};

const CONSUMABLE_CATALOG = [
  { id: 'shield-cell', name: 'Shield Cell', tier: 1, value: [20, 30], effect: 'shieldBurst' },
  { id: 'signal-purge', name: 'Signal Purge', tier: 1, value: [25, 35], effect: 'signalPurge' },
  { id: 'time-dilator', name: 'Time Dilator', tier: 2, value: [60, 90], effect: 'timeSlowLocal' },
  { id: 'breach-flare', name: 'Breach Flare', tier: 2, value: [80, 120], effect: 'breachFlare' },
  { id: 'signal-flare', name: 'Signal Flare', tier: 1, value: [20, 35], effect: 'signalFlare' },
  { id: 'emergency-thrust', name: 'Emergency Thrust', tier: 2, value: [70, 100], effect: 'emergencyThrust' },
  { id: 'cargo-jettison', name: 'Cargo Jettison', tier: 1, value: [15, 20], effect: 'cargoJettison' },
  { id: 'well-repulsor', name: 'Well Repulsor', tier: 3, value: [200, 280], effect: 'wellRepulsor' },
  { id: 'foam-anchor', name: 'Foam Anchor', tier: 2, value: [70, 105], effect: 'shieldBurst' },
  { id: 'dead-air-ampoule', name: 'Dead-Air Ampoule', tier: 2, value: [85, 125], effect: 'timeSlowLocal' },
  { id: 'crown-breach-match', name: 'Crown Breach Match', tier: 3, value: [220, 320], effect: 'breachFlare' },
];

module.exports = {
  ARTIFACT_SPECIAL_IDS,
  CONSUMABLE_EFFECT_IDS,
  ITEM_CATALOG,
  CONSUMABLE_CATALOG,
};
